package main

// import _ "github.com/Gavin-Gong/learn-go/example"
import (
	"fmt"

	_ "github.com/Gavin-Gong/learn-go/crawler"
	// middleware "github.com/Gavin-Gong/learn-go/web/04-middleware"
)

// import _ "github.com/Gavin-Gong/learn-go/practice/downloader"
// import "github.com/Gavin-Gong/learn-go/practice/spotlight-pic"
import "github.com/Gavin-Gong/learn-go/practice/downloader"

// import "github.com/Gavin-Gong/learn-go/practice/concurrent-attack"

func main() {
	// crawler.Start()
	// downloader.Start()
	// basic.Start()
	// fileSrv.Start()
	// router.Start()
	// middleware.Start()

	list := []string{
		"strategy/AU/价值投资.jpg",
		"strategy/AU/动量选股.jpg",
		"strategy/AU/平衡选股.jpg",
		"strategy/AU/成长速度.jpg",
		"strategy/AU/投研荐股.jpg",
		"strategy/AU/新兴企业.jpg",
		"strategy/AU/波动选股.jpg",
		"strategy/AU/盈利质量.jpg",
		"strategy/AU/资本效率.jpg",
		"strategy/CH/价值投资.jpg",
		"strategy/CH/动量选股.jpg",
		"strategy/CH/平衡选股/CH_middle_size.jpg",
		"strategy/CH/平衡选股/CH_mini_size.jpg",
		"strategy/CH/平衡选股/平衡选股.jpg",
		"strategy/CH/平衡选股/平衡选股2.jpg",
		"strategy/CH/成长速度.jpg",
		"strategy/CH/新兴企业.jpg",
		"strategy/CH/波动选股.jpg",
		"strategy/CH/热门风格.jpg",
		"strategy/CH/独创优化.jpg",
		"strategy/CH/盈利质量.jpg",
		"strategy/CH/资本效率.jpg",
		"strategy/CN/价值投资.jpg",
		"strategy/CN/动量选股.jpg",
		"strategy/CN/均衡.jpg",
		"strategy/CN/平衡选股.jpg",
		"strategy/CN/成长速度.jpg",
		"strategy/CN/投研荐股.jpg",
		"strategy/CN/新兴企业.jpg",
		"strategy/CN/波动选股.jpg",
		"strategy/CN/热门风格.jpg",
		"strategy/CN/盈利质量.jpg",
		"strategy/CN/精选行业.jpg",
		"strategy/CN/资本效率.jpg",
		"strategy/DE/gm_DAX_Analyst Expectations_5.jpg",
		"strategy/DE/gm_DAX_Capital Efficiency_5.jpg",
		"strategy/DE/gm_DAX_Earnings Quality_5.jpg",
		"strategy/DE/gm_DAX_Historical Growth_5.jpg",
		"strategy/DE/gm_DAX_Price Momentum_5.jpg",
		"strategy/DE/gm_DAX_Size_5.jpg",
		"strategy/DE/gm_DAX_Valuation_5.jpg",
		"strategy/DE/gm_DAX_Volatility_5.jpg",
		"strategy/DE/gm_DAX_equal_weight_32_notiming.jpg",
		"strategy/DE/gm_DAX_timing_opt_notiming_noselect.jpg",
		"strategy/DE/gm_GMALL_Analyst Expectations_8.jpg",
		"strategy/DE/gm_GMALL_Capital Efficiency_8.jpg",
		"strategy/DE/gm_GMALL_Earnings Quality_8.jpg",
		"strategy/DE/gm_GMALL_Historical Growth_8.jpg",
		"strategy/DE/gm_GMALL_Price Momentum_8.jpg",
		"strategy/DE/gm_GMALL_Size_8.jpg",
		"strategy/DE/gm_GMALL_Valuation_8.jpg",
		"strategy/DE/gm_GMALL_Volatility_8.jpg",
		"strategy/DE/gm_GMALL_equal_weight_14.jpg",
		"strategy/DE/gm_GMALL_equal_weight_21.jpg",
		"strategy/DE/gm_GMALL_timing_magic_20.jpg",
		"strategy/DE/价值投资.jpg",
		"strategy/DE/动量选股.jpg",
		"strategy/DE/平衡选股.jpg",
		"strategy/DE/成长速度.jpg",
		"strategy/DE/投研荐股.jpg",
		"strategy/DE/新兴企业.jpg",
		"strategy/DE/波动选股.jpg",
		"strategy/DE/独创优化.jpg",
		"strategy/DE/盈利质量.jpg",
		"strategy/DE/经典优化.jpg",
		"strategy/DE/资本效率.jpg",
		"strategy/ES/价值投资.jpg",
		"strategy/ES/动量选股.jpg",
		"strategy/ES/平衡选股.jpg",
		"strategy/ES/成长速度.jpg",
		"strategy/ES/投研荐股.jpg",
		"strategy/ES/新兴企业.jpg",
		"strategy/ES/波动选股.jpg",
		"strategy/ES/热门风格/ES_mini_size.jpg",
		"strategy/ES/热门风格/ES_small_size.jpg",
		"strategy/ES/盈利质量.jpg",
		"strategy/ES/精选行业.jpg",
		"strategy/ES/资本效率.jpg",
		"strategy/FR/价值投资 .jpg",
		"strategy/FR/价值投资.jpg",
		"strategy/FR/企业估值.jpg",
		"strategy/FR/动量选股.jpg",
		"strategy/FR/平衡选股.jpg",
		"strategy/FR/成长速度.jpg",
		"strategy/FR/投研荐股.jpg",
		"strategy/FR/新兴企业.jpg",
		"strategy/FR/波动选股.jpg",
		"strategy/FR/热门风格.jpg",
		"strategy/FR/独创优化.jpg",
		"strategy/FR/盈利质量.jpg",
		"strategy/FR/经典优化.jpg",
		"strategy/FR/资本效率.jpg",
		"strategy/HK/价值投资.jpg",
		"strategy/HK/动量选股.jpg",
		"strategy/HK/平衡选股.jpg",
		"strategy/HK/成长速度.jpg",
		"strategy/HK/投研荐股.jpg",
		"strategy/HK/新兴企业.jpg",
		"strategy/HK/波动选股.jpg",
		"strategy/HK/热门风格.jpg",
		"strategy/HK/独创优化.jpg",
		"strategy/HK/盈利质量.jpg",
		"strategy/HK/精选行业.jpg",
		"strategy/HK/资本效率.jpg",
		"strategy/IT/价值投资.jpg",
		"strategy/IT/动量选股.jpg",
		"strategy/IT/平衡选股.jpg",
		"strategy/IT/成长速度.jpg",
		"strategy/IT/投研荐股.jpg",
		"strategy/IT/新兴企业.jpg",
		"strategy/IT/波动选股.jpg",
		"strategy/IT/热门风格.jpg",
		"strategy/IT/盈利质量.jpg",
		"strategy/IT/经典优化.jpg",
		"strategy/IT/资本效率.jpg",
		"strategy/JP/价值投资.jpg",
		"strategy/JP/动量选股.jpg",
		"strategy/JP/平衡选股.jpg",
		"strategy/JP/成长速度.jpg",
		"strategy/JP/投研荐股.jpg",
		"strategy/JP/新兴企业.jpg",
		"strategy/JP/波动选股.jpg",
		"strategy/JP/热门风格.jpg",
		"strategy/JP/独创优化.jpg",
		"strategy/JP/盈利质量.jpg",
		"strategy/JP/精选行业.jpg",
		"strategy/JP/资本效率.jpg",
		"strategy/SE/价值投资.jpg",
		"strategy/SE/动量选股.jpg",
		"strategy/SE/平衡选股.jpg",
		"strategy/SE/成长速度.jpg",
		"strategy/SE/投研荐股.jpg",
		"strategy/SE/新兴企业.jpg",
		"strategy/SE/波动选股.jpg",
		"strategy/SE/热门风格.jpg",
		"strategy/SE/盈利质量.jpg",
		"strategy/SE/资本效率.jpg",
		"strategy/UK/价值投资.jpg",
		"strategy/UK/动量选股.jpg",
		"strategy/UK/平衡选股.jpg",
		"strategy/UK/成长速度.jpg",
		"strategy/UK/投研荐股.jpg",
		"strategy/UK/新兴企业.jpg",
		"strategy/UK/波动选股.jpg",
		"strategy/UK/热门风格.jpg",
		"strategy/UK/盈利质量.jpg",
		"strategy/UK/精选行业.jpg",
		"strategy/UK/经典优化.jpg",
		"strategy/UK/资本效率.jpg",
		"strategy/US/价值投资.jpg",
		"strategy/US/动量选股.jpg",
		"strategy/US/平衡选股.jpg",
		"strategy/US/成长速度.jpg",
		"strategy/US/投研荐股.jpg",
		"strategy/US/新兴企业.jpg",
		"strategy/US/波动选股.jpg",
		"strategy/US/热门风格.jpg",
		"strategy/US/盈利质量.jpg",
		"strategy/US/经典优化.jpg",
		"strategy/US/资本效率.jpg",
		"strategy/VN/价值投资.jpg",
		"strategy/VN/动量选股.jpg",
		"strategy/VN/平衡选股/insurance.jpg",
		"strategy/VN/平衡选股/yuenanfangdicha.jpg",
		"strategy/VN/平衡选股/yuenangonggongshiye.jpg",
		"strategy/VN/平衡选股/yuenangongyeyuanliao.jpg",
		"strategy/VN/平衡选股/yuenanhuzhiming.jpg",
		"strategy/VN/平衡选股/yuenanjichubankuai.jpg",
		"strategy/VN/平衡选股/yuenanlingshou.jpg",
		"strategy/VN/成长速度.jpg",
		"strategy/VN/投研荐股.jpg",
		"strategy/VN/新兴企业.jpg",
		"strategy/VN/波动选股.jpg",
		"strategy/VN/盈利质量.jpg",
		"strategy/VN/资本效率.jpg",
	}
	for k, v := range list {
		err := downloader.DownLoad(fmt.Sprintf("./temp/%d.jpg", k+1), fmt.Sprintf("http://plan.static.qsbrokers.com/%s", v))
		fmt.Println(err)
	}
	// attacker.Start()
}
